#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-workload-token
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: eknathreddy09
  password: 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
---
apiVersion: v1
kind: Secret
metadata:
  name: github-workload-token
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: eknathreddy09
  password: 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
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-sa
secrets:
  - name: registries-credentials
  - name: cosign
  - name: gitlab-workload-token
  - name: github-workload-token
imagePullSecrets:
  - name: registries-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-sa-permit-deliverable
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deliverable
subjects:
  - kind: ServiceAccount
    name: workload-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-sa-permit-workload
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload
subjects:
  - kind: ServiceAccount
    name: workload-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: cosign
  annotations:
    kpack.io/cosign.docker-media-types: "1"
type: Opaque
data:
  cosign.key: #@ base64.encode('cosign.key')
  cosign.password: #@ base64.encode('cosign.password')
  cosign.pub: #@ base64.encode('cosign.pub')